#!/usr/bin/env bash
# Provision THIS Mac for Developer ID signing + notarization using secrets
# stored in Google Secret Manager. Safe to re-run (idempotent).
#
# What it does:
#   1. Pulls the Developer ID cert + notary API key from Secret Manager.
#   2. Creates a dedicated 'oxos-signing' keychain and imports the cert so
#      codesign can use it non-interactively (no GUI password prompt).
#   3. Writes the notary API key to ~/.config/oxos-signing/ and an env.sh that
#      both the Slates (Tauri) and Anvil (make-app.sh) builds source.
#
# Usage:  ./provision.sh        (run once per machine; re-run to rotate)
set -euo pipefail
cd "$(dirname "$0")"
source ./config.sh

check_gcloud_auth
require security
require codesign
xcrun notarytool --version >/dev/null 2>&1 || die "notarytool unavailable (install Xcode Command Line Tools)"

echo "▸ pulling secrets from project '$PROJECT'…"
mkdir -p "$SIGNING_HOME"; chmod 700 "$SIGNING_HOME"
tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT

secret_get "$SECRET_P12"           | base64 -D -o "$tmp/cert.p12"
secret_get "$SECRET_NOTARY_P8"     | base64 -D -o "$P8_PATH"; chmod 600 "$P8_PATH"
P12_PASS="$(secret_get "$SECRET_P12_PASS")"
IDENTITY="$(secret_get "$SECRET_IDENTITY")"
KEY_ID="$(secret_get "$SECRET_NOTARY_KEY_ID")"
ISSUER="$(secret_get "$SECRET_NOTARY_ISSUER")"

# --- dedicated keychain -----------------------------------------------------
# Per-machine random keychain password; never leaves this Mac.
KC_PASS="$(security find-generic-password -s oxos-signing-kc -w 2>/dev/null || true)"
if [ -z "$KC_PASS" ]; then
  KC_PASS="$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 40)"
  security add-generic-password -s oxos-signing-kc -a "$USER" -w "$KC_PASS" 2>/dev/null || true
fi

if [ ! -f "$KEYCHAIN_PATH" ]; then
  echo "▸ creating keychain $KEYCHAIN_NAME"
  security create-keychain -p "$KC_PASS" "$KEYCHAIN_PATH"
fi
security set-keychain-settings "$KEYCHAIN_PATH"            # no auto-lock timeout
security unlock-keychain -p "$KC_PASS" "$KEYCHAIN_PATH"

# Add to the user search list without duplicating it.
others="$(security list-keychains -d user | sed -e 's/^[[:space:]]*"//' -e 's/"$//' | grep -v "$KEYCHAIN_NAME" || true)"
# shellcheck disable=SC2086
security list-keychains -d user -s "$KEYCHAIN_PATH" $others

# Import the cert (idempotent: ignore "already exists").
security import "$tmp/cert.p12" -k "$KEYCHAIN_PATH" -P "$P12_PASS" \
  -T /usr/bin/codesign -T /usr/bin/security 2>/dev/null || true
# Allow codesign to use the key without an interactive prompt.
security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KC_PASS" "$KEYCHAIN_PATH" >/dev/null

# --- verify the identity is usable -----------------------------------------
if ! security find-identity -v -p codesigning "$KEYCHAIN_PATH" | grep -q "$IDENTITY"; then
  die "identity not found in keychain after import: $IDENTITY"
fi
echo "✓ signing identity ready: $IDENTITY"

# --- env file the builds source --------------------------------------------
cat > "$ENV_FILE" <<EOF
# Generated by provision.sh — source before building Slates or Anvil.
export APPLE_SIGNING_IDENTITY="$IDENTITY"
export APPLE_API_KEY="$KEY_ID"          # App Store Connect Key ID
export APPLE_API_ISSUER="$ISSUER"       # App Store Connect Issuer ID
export APPLE_API_KEY_PATH="$P8_PATH"    # path to the AuthKey .p8
export SIGN_ID="\$APPLE_SIGNING_IDENTITY"  # alias consumed by Anvil's make-app.sh
EOF
chmod 600 "$ENV_FILE"

echo "✓ wrote $ENV_FILE"
echo
echo "Next: in any build shell run"
echo "    source \"$ENV_FILE\""
echo "  then build as usual — Slates: 'npm run tauri:build', Anvil: './make-app.sh'."
echo "Verify a build with:  spctl -a -vvv --type exec /path/to/App.app"
